class ParitySurface {
  const ParitySurface(this.group, this.name, this.webSource, {this.kind = 'page'});

  final String group;
  final String name;
  final String webSource;
  final String kind;
}

const parityCatalog = <ParitySurface>[
  ParitySurface('Routes', 'Sign in / Sign up shell', 'routes/auth.jsx'),
  ParitySurface('Routes', 'Forgot password', 'components/auth/forgotPass.jsx'),
  ParitySurface('Routes', 'Link device', 'components/auth/linkDevice.jsx'),
  ParitySurface('Routes', 'QR scanner', 'components/auth/qrScanner.jsx'),
  ParitySurface('Routes', 'Social auth', 'components/auth/socialAuth.jsx'),
  ParitySurface('Routes', 'Verify account', 'routes/verify.jsx'),
  ParitySurface('Routes', 'Inactive account', 'routes/inactive.jsx'),
  ParitySurface('Routes', 'Chat application shell', 'routes/chat.jsx'),

  ParitySurface('Foreground', 'Chats', 'components/chat/foreground/inbox.jsx'),
  ParitySurface('Foreground', 'Calls', 'components/chat/foreground/inbox.jsx'),
  ParitySurface('Foreground', 'Status rail', 'components/chat/foreground/inbox.jsx'),
  ParitySurface('Foreground', 'Archive', 'components/chat/foreground/inbox.jsx'),
  ParitySurface('Foreground', 'Lists', 'components/chat/foreground/inbox.jsx'),
  ParitySurface('Foreground', 'Starred messages', 'components/chat/foreground/inbox.jsx'),
  ParitySurface('Foreground', 'Chat filters', 'components/chat/foreground/header.jsx'),
  ParitySurface('Foreground', 'Mobile bottom navigation', 'components/chat/foreground/mobileNav.jsx'),
  ParitySurface('Foreground', 'Mobile side rail', 'components/chat/foreground/sidebar.jsx'),
  ParitySurface('Foreground', 'Overflow mini menu', 'components/chat/foreground/minibox.jsx', kind: 'sheet'),
  ParitySurface('Foreground', 'Open contact', 'components/chat/foreground/openContact.jsx', kind: 'sheet'),

  ParitySurface('Pages', 'Contacts', 'pages/contact.jsx'),
  ParitySurface('Pages', 'Communities', 'pages/communities.jsx'),
  ParitySurface('Pages', 'Channels', 'pages/channels.jsx'),
  ParitySurface('Pages', 'Status', 'pages/status.jsx'),
  ParitySurface('Pages', 'Profile', 'pages/profile.jsx'),
  ParitySurface('Pages', 'Settings', 'pages/setting.jsx'),
  ParitySurface('Pages', 'Media', 'pages/media.jsx'),
  ParitySurface('Pages', 'Policy', 'pages/policy.jsx'),
  ParitySurface('Pages', 'License', 'pages/license.jsx'),
  ParitySurface('Pages', 'New group', 'pages/newGroup.jsx'),
  ParitySurface('Pages', 'Friend profile', 'pages/friendProfile.jsx'),
  ParitySurface('Pages', 'Group profile', 'pages/groupProfile.jsx'),
  ParitySurface('Pages', 'Channel profile', 'pages/channelProfile.jsx'),
  ParitySurface('Pages', 'Group participants', 'pages/groupParticipant.jsx'),
  ParitySurface('Pages', 'Add participant', 'pages/addParticipant.jsx'),

  ParitySurface('Room', 'Room header', 'components/chat/room/header.jsx'),
  ParitySurface('Room', 'Pinned messages', 'components/chat/room/header.jsx'),
  ParitySurface('Room', 'Pin history', 'components/chat/room/header.jsx', kind: 'sheet'),
  ParitySurface('Room', 'Search in chat', 'components/chat/room/header.jsx'),
  ParitySurface('Room', 'Message monitor', 'components/chat/room/monitor.jsx'),
  ParitySurface('Room', 'Message selection', 'components/chat/room/monitor.jsx'),
  ParitySurface('Room', 'Reply / forward / reaction / edit', 'components/chat/room/monitor.jsx', kind: 'sheet'),
  ParitySurface('Room', 'Media / link / location / poll / event message cards', 'components/chat/room/monitor.jsx'),
  ParitySurface('Room', 'Composer', 'components/chat/room/send.jsx'),
  ParitySurface('Room', 'Emoji board', 'components/chat/room/emojiBoard.jsx', kind: 'sheet'),
  ParitySurface('Room', 'Voice recorder', 'components/chat/room/send.jsx'),
  ParitySurface('Room', 'Scheduled messages', 'components/chat/room/send.jsx', kind: 'sheet'),
  ParitySurface('Room', 'View-once text', 'components/chat/room/send.jsx'),
  ParitySurface('Room', 'Slow mode / admin-only send state', 'components/chat/room/send.jsx'),

  ParitySurface('Chat tools', 'Search', 'components/chat/GlobalChatTools.jsx', kind: 'sheet'),
  ParitySurface('Chat tools', 'Message requests', 'components/chat/GlobalChatTools.jsx', kind: 'sheet'),
  ParitySurface('Chat tools', 'Mentions', 'components/chat/GlobalChatTools.jsx', kind: 'sheet'),
  ParitySurface('Chat tools', 'Topics', 'components/chat/GlobalChatTools.jsx', kind: 'sheet'),
  ParitySurface('Chat tools', 'Security / E2EE', 'components/chat/GlobalChatTools.jsx', kind: 'sheet'),
  ParitySurface('Chat tools', 'Outbox / retry', 'components/chat/GlobalChatTools.jsx', kind: 'sheet'),
  ParitySurface('Chat tools', 'Message details / receipts', 'components/chat/GlobalChatTools.jsx', kind: 'sheet'),

  ParitySurface('Settings', 'Account settings', 'pages/setting.jsx'),
  ParitySurface('Settings', 'Devices', 'pages/setting.jsx'),
  ParitySurface('Settings', 'Privacy', 'pages/setting.jsx'),
  ParitySurface('Settings', 'Chat settings', 'pages/setting.jsx'),
  ParitySurface('Settings', 'Notifications', 'pages/setting.jsx'),
  ParitySurface('Settings', 'Voice & Video', 'pages/setting.jsx'),
  ParitySurface('Settings', 'Google 2FA', 'pages/setting.jsx'),
  ParitySurface('Settings', 'App lock', 'pages/setting.jsx'),
  ParitySurface('Settings', 'Recovery codes', 'pages/setting.jsx'),
  ParitySurface('Settings', 'Keyboard shortcuts', 'pages/setting.jsx'),
  ParitySurface('Settings', 'Backup / restore', 'pages/setting.jsx'),
  ParitySurface('Settings', 'Google Drive connection', 'pages/setting.jsx'),

  ParitySurface('Status', 'Status composer', 'pages/status.jsx'),
  ParitySurface('Status', 'Status viewer', 'pages/status.jsx'),
  ParitySurface('Status', 'Status activity', 'pages/status.jsx', kind: 'sheet'),
  ParitySurface('Status', 'Status reactions / replies / mentions', 'pages/status.jsx', kind: 'sheet'),

  ParitySurface('Calls', 'Start call', 'components/modals/callStart.jsx', kind: 'sheet'),
  ParitySurface('Calls', '1:1 call panel', 'components/modals/callPanel.jsx'),
  ParitySurface('Calls', 'Call runtime', 'components/modals/callPanelRuntime.jsx'),
  ParitySurface('Calls', 'Group call / LiveKit', 'components/modals/groupCallLiveKit.jsx'),
  ParitySurface('Calls', 'Global incoming call layer', 'components/calling/globalCallLayer.jsx'),

  ParitySurface('Modals', 'Attach menu', 'components/modals/attachMenu.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Attach contact', 'components/modals/attachContact.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Attach event', 'components/modals/attachEvent.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Attach poll', 'components/modals/attachPoll.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Attach sticker', 'components/modals/attachSticker.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Avatar upload', 'components/modals/avatarUpload.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Image cropper', 'components/modals/imageCropper.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Change password', 'components/modals/changePass.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Delete account', 'components/modals/deleteAcc.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Confirm add participant', 'components/modals/confirmAddParticipant.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Confirm delete chat', 'components/modals/confirmDeleteChat.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Confirm delete chat + inbox', 'components/modals/confirmDeleteChatAndInbox.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Confirm delete contact', 'components/modals/confirmDeleteContact.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Confirm exit group', 'components/modals/confirmExitGroup.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Confirm new group', 'components/modals/confirmNewGroup.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Edit group', 'components/modals/editGroup.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Feedback', 'components/modals/feedback.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Group context menu', 'components/modals/groupContextMenu.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Inbox context menu', 'components/modals/inboxMenu.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Media preview', 'components/modals/media.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'New contact', 'components/modals/newContact.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Photo full screen', 'components/modals/photoFull.jsx'),
  ParitySurface('Modals', 'QR profile / device', 'components/modals/qr.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Record voice', 'components/modals/recordVoice.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Room appearance', 'components/modals/roomAppearance.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Room header menu', 'components/modals/roomHeaderMenu.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Send file', 'components/modals/sendFile.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Share contact', 'components/modals/shareContact.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Sign out', 'components/modals/signout.jsx', kind: 'sheet'),
  ParitySurface('Modals', 'Webcam capture', 'components/modals/webcam.jsx', kind: 'sheet'),
];
